
ns= {
  'et':'http://ns.exiftool.ca/1.0/',
  'ExifTool':'http://ns.exiftool.ca/ExifTool/1.0/',
  'System':'http://ns.exiftool.ca/File/System/1.0/',
  'File':'http://ns.exiftool.ca/File/1.0/',
  'ZIP':'http://ns.exiftool.ca/ZIP/ZIP/1.0/',
  'XML':'http://ns.exiftool.ca/XML/XML/1.0/',

  'aux'       : 'http://ns.adobe.com/exif/1.0/aux/',
  'album'     : 'http://ns.adobe.com/album/1.0/',
  'cc'        : 'http://creativecommons.org/ns#', # changed 2007/12/21 - PH
  'crs'       : 'http://ns.adobe.com/camera-raw-settings/1.0/',
  'crss'      : 'http://ns.adobe.com/camera-raw-saved-settings/1.0/',
  'dc'        : 'http://purl.org/dc/elements/1.1/',
  'exif'      : 'http://ns.adobe.com/exif/1.0/',
  'iX'        : 'http://ns.adobe.com/iX/1.0/',
  'pdf'       : 'http://ns.adobe.com/pdf/1.3/',
  'pdfx'      : 'http://ns.adobe.com/pdfx/1.3/',
  'photoshop' : 'http://ns.adobe.com/photoshop/1.0/',
  'rdf'       : 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
  'rdfs'      : 'http://www.w3.org/2000/01/rdf-schema#',
  'stDim'     : 'http://ns.adobe.com/xap/1.0/sType/Dimensions#',
  'stArea'    : 'http://ns.adobe.com/xap/1.0/sType/Area#',
  'stEvt'     : 'http://ns.adobe.com/xap/1.0/sType/ResourceEvent#',
  'stFnt'     : 'http://ns.adobe.com/xap/1.0/sType/Font#',
  'stJob'     : 'http://ns.adobe.com/xap/1.0/sType/Job#',
  'stRef'     : 'http://ns.adobe.com/xap/1.0/sType/ResourceRef#',
  'stVer'     : 'http://ns.adobe.com/xap/1.0/sType/Version#',
  'stMfs'     : 'http://ns.adobe.com/xap/1.0/sType/ManifestItem#',
  'tiff'      : 'http://ns.adobe.com/tiff/1.0/',
  'x'        : 'adobe:ns:meta/',
  'xmpG'      : 'http://ns.adobe.com/xap/1.0/g/',
  'xmpGImg'   : 'http://ns.adobe.com/xap/1.0/g/img/',
  'xmp'       : 'http://ns.adobe.com/xap/1.0/',
  'xmpBJ'     : 'http://ns.adobe.com/xap/1.0/bj/',
  'xmpDM'     : 'http://ns.adobe.com/xmp/1.0/DynamicMedia/',
  'xmpMM'     : 'http://ns.adobe.com/xap/1.0/mm/',
  'xmpRights' : 'http://ns.adobe.com/xap/1.0/rights/',
  'xmpNote'   : 'http://ns.adobe.com/xmp/note/',
  'xmpTPg'    : 'http://ns.adobe.com/xap/1.0/t/pg/',
  'xmpidq'    : 'http://ns.adobe.com/xmp/Identifier/qual/1.0/',
  'xmpPLUS'   : 'http://ns.adobe.com/xap/1.0/PLUS/',
  'dex'       : 'http://ns.optimasc.com/dex/1.0/',
  'mediapro'  : 'http://ns.iview-multimedia.com/mediapro/1.0/',
  'Iptc4xmpCore' : 'http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/',
  'Iptc4xmpExt' : 'http://iptc.org/std/Iptc4xmpExt/2008-02-29/',
  'MicrosoftPhoto' : 'http://ns.microsoft.com/photo/1.0',
  'MP1'       : 'http://ns.microsoft.com/photo/1.1', #PH (MP1 is fabricated)
  'MP'        : 'http://ns.microsoft.com/photo/1.2/',
  'MPRI'      : 'http://ns.microsoft.com/photo/1.2/t/RegionInfo#',
  'MPReg'     : 'http://ns.microsoft.com/photo/1.2/t/Region#',
  'lr'        : 'http://ns.adobe.com/lightroom/1.0/',
  'DICOM'     : 'http://ns.adobe.com/DICOM/',
  'svg'       : 'http://www.w3.org/2000/svg',
  # namespaces defined in XMP2.pl:
  'plus'      : 'http://ns.useplus.org/ldf/xmp/1.0/',
  'prism'     : 'http://prismstandard.org/namespaces/basic/2.1/',
  'prl'       : 'http://prismstandard.org/namespaces/prl/2.1/',
  'pur'       : 'http://prismstandard.org/namespaces/prismusagerights/2.1/',
  'acdsee'    : 'http://ns.acdsee.com/iptc/1.0/',
  'digiKam'   : 'http://www.digikam.org/ns/1.0/',
  'swf'       : 'http://ns.adobe.com/swf/1.0',
  'cell'      : 'http://developer.sonyericsson.com/cell/1.0/',
  'mwg-rs'   : 'http://www.metadataworkinggroup.com/schemas/regions/',
  'mwg-kw'   : 'http://www.metadataworkinggroup.com/schemas/keywords/',
  'mwg-coll' : 'http://www.metadataworkinggroup.com/schemas/collections/',

# Found
'AC3':'http://ns.exiftool.ca/M2TS/AC3/1.0/',
'AIFF':'http://ns.exiftool.ca/AIFF/AIFF/1.0/',
'APE':'http://ns.exiftool.ca/APE/APE/1.0/',
'ASF':'http://ns.exiftool.ca/ASF/ASF/1.0/',
'AVI1':'http://ns.exiftool.ca/APP0/AVI1/1.0/',
'Adobe':'http://ns.exiftool.ca/APP14/Adobe/1.0/',
'AdobeCM':'http://ns.exiftool.ca/APP13/AdobeCM/1.0/',
'CIFF':'http://ns.exiftool.ca/MakerNotes/CIFF/1.0/',
'Canon':'http://ns.exiftool.ca/MakerNotes/Canon/1.0/',
'CanonCustom':'http://ns.exiftool.ca/MakerNotes/CanonCustom/1.0/',
'CanonRaw':'http://ns.exiftool.ca/MakerNotes/CanonRaw/1.0/',
'CanonVRD':'http://ns.exiftool.ca/CanonVRD/CanonVRD/1.0/',
'Casio':'http://ns.exiftool.ca/MakerNotes/Casio/1.0/',
'Composite':'http://ns.exiftool.ca/Composite/1.0/',
'DV':'http://ns.exiftool.ca/DV/DV/1.0/',
'DjVu':'http://ns.exiftool.ca/DjVu/DjVu/1.0/',
'DjVu-Meta':'http://ns.exiftool.ca/DjVu/DjVu-Meta/1.0/',
'Ducky':'http://ns.exiftool.ca/Ducky/Ducky/1.0/',
'EXE':'http://ns.exiftool.ca/EXE/EXE/1.0/',
'ExifIFD':'http://ns.exiftool.ca/EXIF/ExifIFD/1.0/',
'FLAC':'http://ns.exiftool.ca/FLAC/FLAC/1.0/',
'Flash':'http://ns.exiftool.ca/Flash/Flash/1.0/',
'FlashPix':'http://ns.exiftool.ca/FlashPix/FlashPix/1.0/',
'Font':'http://ns.exiftool.ca/Font/Font/1.0/',
'FotoStation':'http://ns.exiftool.ca/FotoStation/FotoStation/1.0/',
'FujiFilm':'http://ns.exiftool.ca/MakerNotes/FujiFilm/1.0/',
'GE':'http://ns.exiftool.ca/MakerNotes/GE/1.0/',
'GIF':'http://ns.exiftool.ca/GIF/GIF/1.0/',
'GIMP':'http://ns.exiftool.ca/GIMP/GIMP/1.0/',
'GPS':'http://ns.exiftool.ca/EXIF/GPS/1.0/',
'GeoTiff':'http://ns.exiftool.ca/GeoTiff/GeoTiff/1.0/',
'GraphConv':'http://ns.exiftool.ca/APP15/GraphConv/1.0/',
'H264':'http://ns.exiftool.ca/H264/H264/1.0/',
'HTML':'http://ns.exiftool.ca/HTML/HTML/1.0/',
'HTML-dc':'http://ns.exiftool.ca/HTML/HTML-dc/1.0/',
'HTML-ncc':'http://ns.exiftool.ca/HTML/HTML-ncc/1.0/',
'HTML-office':'http://ns.exiftool.ca/HTML/HTML-office/1.0/',
'HTML-prod':'http://ns.exiftool.ca/HTML/HTML-prod/1.0/',
'HTTP-equiv':'http://ns.exiftool.ca/HTML/HTTP-equiv/1.0/',
'ICC-header':'http://ns.exiftool.ca/ICC_Profile/ICC-header/1.0/',
'ICC-meas':'http://ns.exiftool.ca/ICC_Profile/ICC-meas/1.0/',
'ICC-view':'http://ns.exiftool.ca/ICC_Profile/ICC-view/1.0/',
'ICC_Profile':'http://ns.exiftool.ca/ICC_Profile/ICC_Profile/1.0/',
'ID3v1':'http://ns.exiftool.ca/ID3/ID3v1/1.0/',
'ID3v2_2':'http://ns.exiftool.ca/ID3/ID3v2_2/1.0/',
'IFD0':'http://ns.exiftool.ca/EXIF/IFD0/1.0/',
'IFD1':'http://ns.exiftool.ca/EXIF/IFD1/1.0/',
'IFD2':'http://ns.exiftool.ca/EXIF/IFD2/1.0/',
'IFD3':'http://ns.exiftool.ca/EXIF/IFD3/1.0/',
'IPTC':'http://ns.exiftool.ca/IPTC/IPTC/1.0/',
'IPTC2':'http://ns.exiftool.ca/IPTC/IPTC2/1.0/',
'IPTC3':'http://ns.exiftool.ca/IPTC/IPTC3/1.0/',
'ITC':'http://ns.exiftool.ca/ITC/ITC/1.0/',
'InteropIFD':'http://ns.exiftool.ca/EXIF/InteropIFD/1.0/',
'JFIF':'http://ns.exiftool.ca/JFIF/JFIF/1.0/',
'JVC':'http://ns.exiftool.ca/MakerNotes/JVC/1.0/',
'Jpeg2000':'http://ns.exiftool.ca/Jpeg2000/Jpeg2000/1.0/',
'Kodak':'http://ns.exiftool.ca/MakerNotes/Kodak/1.0/',
'KyoceraRaw':'http://ns.exiftool.ca/MakerNotes/KyoceraRaw/1.0/',
'LNK':'http://ns.exiftool.ca/LNK/LNK/1.0/',
'M2TS':'http://ns.exiftool.ca/M2TS/M2TS/1.0/',
'MAC':'http://ns.exiftool.ca/APE/MAC/1.0/',
'MIE-Camera':'http://ns.exiftool.ca/MIE/MIE-Camera/1.0/',
'MIE-Doc':'http://ns.exiftool.ca/MIE/MIE-Doc/1.0/',
'MIE-Flash':'http://ns.exiftool.ca/MIE/MIE-Flash/1.0/',
'MIE-Geo':'http://ns.exiftool.ca/MIE/MIE-Geo/1.0/',
'MIE-Image':'http://ns.exiftool.ca/MIE/MIE-Image/1.0/',
'MIE-Lens':'http://ns.exiftool.ca/MIE/MIE-Lens/1.0/',
'MIE-Main':'http://ns.exiftool.ca/MIE/MIE-Main/1.0/',
'MIE-Orient':'http://ns.exiftool.ca/MIE/MIE-Orient/1.0/',
'MIE-Thumbnail':'http://ns.exiftool.ca/MIE/MIE-Thumbnail/1.0/',
'MIFF':'http://ns.exiftool.ca/MIFF/MIFF/1.0/',
'MPC':'http://ns.exiftool.ca/MPC/MPC/1.0/',
'MPEG':'http://ns.exiftool.ca/MPEG/MPEG/1.0/',
'MPF0':'http://ns.exiftool.ca/MPF/MPF0/1.0/',
'MPImage1':'http://ns.exiftool.ca/MPF/MPImage1/1.0/',
'MPImage2':'http://ns.exiftool.ca/MPF/MPImage2/1.0/',
'MXF':'http://ns.exiftool.ca/MXF/MXF/1.0/',
'Matroska':'http://ns.exiftool.ca/Matroska/Matroska/1.0/',
'MetaIFD':'http://ns.exiftool.ca/Meta/MetaIFD/1.0/',
'Minolta':'http://ns.exiftool.ca/MakerNotes/Minolta/1.0/',
'MinoltaRaw':'http://ns.exiftool.ca/MakerNotes/MinoltaRaw/1.0/',
'NITF':'http://ns.exiftool.ca/APP6/NITF/1.0/',
'Nikon':'http://ns.exiftool.ca/MakerNotes/Nikon/1.0/',
'NikonCapture':'http://ns.exiftool.ca/MakerNotes/NikonCapture/1.0/',
'NikonScan':'http://ns.exiftool.ca/MakerNotes/NikonScan/1.0/',
'Olympus':'http://ns.exiftool.ca/MakerNotes/Olympus/1.0/',
'PDF':'http://ns.exiftool.ca/PDF/PDF/1.0/',
'PNG':'http://ns.exiftool.ca/PNG/PNG/1.0/',
'PSP':'http://ns.exiftool.ca/PSP/PSP/1.0/',
'Panasonic':'http://ns.exiftool.ca/MakerNotes/Panasonic/1.0/',
'Pentax':'http://ns.exiftool.ca/MakerNotes/Pentax/1.0/',
'PhotoMechanic':'http://ns.exiftool.ca/PhotoMechanic/PhotoMechanic/1.0/',
'Photoshop':'http://ns.exiftool.ca/Photoshop/Photoshop/1.0/',
'PictureInfo':'http://ns.exiftool.ca/APP12/PictureInfo/1.0/',
'PostScript':'http://ns.exiftool.ca/PostScript/PostScript/1.0/',
'PreviewIFD':'http://ns.exiftool.ca/MakerNotes/PreviewIFD/1.0/',
'PrintIM':'http://ns.exiftool.ca/PrintIM/PrintIM/1.0/',
'QuickTime':'http://ns.exiftool.ca/QuickTime/QuickTime/1.0/',
'RAF':'http://ns.exiftool.ca/RAF/RAF/1.0/',
'RAF2':'http://ns.exiftool.ca/RAF/RAF2/1.0/',
'RIFF':'http://ns.exiftool.ca/RIFF/RIFF/1.0/',
'RMETA':'http://ns.exiftool.ca/APP5/RMETA/1.0/',
'RSRC':'http://ns.exiftool.ca/RSRC/RSRC/1.0/',
'RTF':'http://ns.exiftool.ca/RTF/RTF/1.0/',
'Real':'http://ns.exiftool.ca/Real/Real/1.0/',
'Real-CONT':'http://ns.exiftool.ca/Real/Real-CONT/1.0/',
'Real-MDPR':'http://ns.exiftool.ca/Real/Real-MDPR/1.0/',
'Real-MDPR2':'http://ns.exiftool.ca/Real/Real-MDPR2/1.0/',
'Real-PROP':'http://ns.exiftool.ca/Real/Real-PROP/1.0/',
'Real-RA4':'http://ns.exiftool.ca/Real/Real-RA4/1.0/',
'Real-RJMD':'http://ns.exiftool.ca/Real/Real-RJMD/1.0/',
'Ricoh':'http://ns.exiftool.ca/MakerNotes/Ricoh/1.0/',
'SPIFF':'http://ns.exiftool.ca/APP8/SPIFF/1.0/',
'SVG':'http://ns.exiftool.ca/SVG/SVG/1.0/',
'SVG-myfoo':'http://ns.exiftool.ca/SVG/SVG-myfoo/1.0/',
'Sanyo':'http://ns.exiftool.ca/MakerNotes/Sanyo/1.0/',
'Sigma':'http://ns.exiftool.ca/MakerNotes/Sigma/1.0/',
'SigmaRaw':'http://ns.exiftool.ca/SigmaRaw/SigmaRaw/1.0/',
'Sony':'http://ns.exiftool.ca/MakerNotes/Sony/1.0/',
'SubIFD':'http://ns.exiftool.ca/EXIF/SubIFD/1.0/',
'SubIFD1':'http://ns.exiftool.ca/EXIF/SubIFD1/1.0/',
'SubIFD2':'http://ns.exiftool.ca/EXIF/SubIFD2/1.0/',
'Track1':'http://ns.exiftool.ca/MXF/Track1/1.0/',
'Track1':'http://ns.exiftool.ca/Matroska/Track1/1.0/',
'Track1':'http://ns.exiftool.ca/QuickTime/Track1/1.0/',
'Track2':'http://ns.exiftool.ca/MXF/Track2/1.0/',
'Track2':'http://ns.exiftool.ca/Matroska/Track2/1.0/',
'Track2':'http://ns.exiftool.ca/QuickTime/Track2/1.0/',
'Vorbis':'http://ns.exiftool.ca/Vorbis/Vorbis/1.0/',
'XML-Composite':'http://ns.exiftool.ca/XML/XML-Composite/1.0/',
'XML-ExifTool':'http://ns.exiftool.ca/XML/XML-ExifTool/1.0/',
'XML-File':'http://ns.exiftool.ca/XML/XML-File/1.0/',
'XMP':'http://ns.exiftool.ca/XMP/XMP/1.0/',
'XMP-album':'http://ns.exiftool.ca/XMP/XMP-album/1.0/',
'XMP-aux':'http://ns.exiftool.ca/XMP/XMP-aux/1.0/',
'XMP-dc':'http://ns.exiftool.ca/XMP/XMP-dc/1.0/',
'XMP-exif':'http://ns.exiftool.ca/XMP/XMP-exif/1.0/',
'XMP-grddl':'http://ns.exiftool.ca/XMP/XMP-grddl/1.0/',
'XMP-iptcCore':'http://ns.exiftool.ca/XMP/XMP-iptcCore/1.0/',
'XMP-iptcExt':'http://ns.exiftool.ca/XMP/XMP-iptcExt/1.0/',
'XMP-meta':'http://ns.exiftool.ca/XMP/XMP-meta/1.0/',
'XMP-mwg-kw':'http://ns.exiftool.ca/XMP/XMP-mwg-kw/1.0/',
'XMP-mwg-rs':'http://ns.exiftool.ca/XMP/XMP-mwg-rs/1.0/',
'XMP-myXMPns':'http://ns.exiftool.ca/XMP/XMP-myXMPns/1.0/',
'XMP-pdf':'http://ns.exiftool.ca/XMP/XMP-pdf/1.0/',
'XMP-pdfx':'http://ns.exiftool.ca/XMP/XMP-pdfx/1.0/',
'XMP-ph':'http://ns.exiftool.ca/XMP/XMP-ph/1.0/',
'XMP-photomech':'http://ns.exiftool.ca/XMP/XMP-photomech/1.0/',
'XMP-photoshop':'http://ns.exiftool.ca/XMP/XMP-photoshop/1.0/',
'XMP-plus':'http://ns.exiftool.ca/XMP/XMP-plus/1.0/',
'XMP-rdf':'http://ns.exiftool.ca/XMP/XMP-rdf/1.0/',
'XMP-test':'http://ns.exiftool.ca/XMP/XMP-test/1.0/',
'XMP-tiff':'http://ns.exiftool.ca/XMP/XMP-tiff/1.0/',
'XMP-x':'http://ns.exiftool.ca/XMP/XMP-x/1.0/',
'XMP-xmp':'http://ns.exiftool.ca/XMP/XMP-xmp/1.0/',
'XMP-xmpBJ':'http://ns.exiftool.ca/XMP/XMP-xmpBJ/1.0/',
'XMP-xmpDM':'http://ns.exiftool.ca/XMP/XMP-xmpDM/1.0/',
'XMP-xmpMM':'http://ns.exiftool.ca/XMP/XMP-xmpMM/1.0/',
'XMP-xmpNote':'http://ns.exiftool.ca/XMP/XMP-xmpNote/1.0/',
'XMP-xmpRights':'http://ns.exiftool.ca/XMP/XMP-xmpRights/1.0/',
'XMP-xsi':'http://ns.exiftool.ca/XMP/XMP-xsi/1.0/',
'XMP-DICOM': 'http://ns.exiftool.ca/XMP/XMP-DICOM/1.0/',
}
